# Generated by Django 6.0.5 on 2026-05-23 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='staff_role',
            field=models.CharField(blank=True, choices=[('cashier', 'Cashier'), ('collector', 'Collector'), ('bookkeeper', 'Bookkeeper'), ('admin_clerk', 'Administrative Clerk')], max_length=20, null=True),
        ),
    ]
