# Generated by Django 6.0.5 on 2026-05-27 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_user_staff_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='staff_role',
            field=models.CharField(blank=True, choices=[('cashier', 'Cashier'), ('collector', 'Collector'), ('admin_clerk', 'Administrative Clerk')], max_length=20, null=True),
        ),
    ]
