# Generated by Django 6.0.5 on 2026-05-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='block_number',
            field=models.PositiveIntegerField(blank=True, help_text='Polygon block number', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='network',
            field=models.CharField(default='local', help_text="'polygon' or 'local'", max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='polygon_tx',
            field=models.CharField(blank=True, help_text='Polygon transaction hash (0x...)', max_length=100, null=True),
        ),
    ]
