# Generated by Django 6.0.5 on 2026-05-31 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_block_number_payment_network_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='hash',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
