# Generated by Django 6.0.3 on 2026-09-18 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0007_loan_cbu_rate_loan_filing_fee_amt_and_more'),
        ('members', '0014_onlineapplication_ocr_birthdate_match_and_more'),
        ('payments', '0003_alter_payment_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_id', models.CharField(blank=True, max_length=30, unique=True)),
                ('principal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('service_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('filing_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('insurance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('savings_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('share_capital_cbu', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_proceeds', models.DecimalField(decimal_places=2, max_digits=12)),
                ('recorded_by', models.CharField(max_length=50)),
                ('hash', models.CharField(blank=True, max_length=64)),
                ('polygon_tx', models.CharField(blank=True, help_text='Polygon transaction hash (0x...)', max_length=100, null=True)),
                ('block_number', models.PositiveIntegerField(blank=True, help_text='Polygon block number', null=True)),
                ('network', models.CharField(default='local', help_text="'polygon' or 'local'", max_length=20)),
                ('released_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='release_record', to='loans.loan')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_releases', to='members.member')),
            ],
            options={
                'db_table': 'loan_releases',
                'ordering': ['-released_at'],
            },
        ),
    ]
