# Generated by Django 6.0.5 on 2026-05-15 10:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='application',
        ),
        migrations.RemoveField(
            model_name='member',
            name='address',
        ),
        migrations.RemoveField(
            model_name='member',
            name='beneficiary',
        ),
        migrations.RemoveField(
            model_name='member',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='member',
            name='civil_status',
        ),
        migrations.RemoveField(
            model_name='member',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='member',
            name='email',
        ),
        migrations.RemoveField(
            model_name='member',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='member',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='member',
            name='id_number',
        ),
        migrations.RemoveField(
            model_name='member',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='member',
            name='middlename',
        ),
        migrations.RemoveField(
            model_name='member',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='member',
            name='relationship',
        ),
        migrations.RemoveField(
            model_name='member',
            name='status',
        ),
        migrations.RemoveField(
            model_name='member',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='member',
            name='valid_id',
        ),
        migrations.AddField(
            model_name='member',
            name='membership_date',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='member',
            name='membership_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Suspended', 'Suspended')], default='Active', max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='plain_password',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='JobProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation', models.CharField(max_length=100)),
                ('job_type', models.CharField(choices=[('Employed', 'Employed'), ('Self-Employed', 'Self-Employed'), ('Business', 'Business'), ('Freelance', 'Freelance'), ('Other', 'Other')], default='Employed', max_length=30)),
                ('monthly_income', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_profile', to='members.member')),
            ],
            options={
                'db_table': 'job_profiles',
            },
        ),
        migrations.CreateModel(
            name='LeafMemberInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('civil_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Widowed', 'Widowed'), ('Separated', 'Separated')], default='Single', max_length=20)),
                ('educational_attainment', models.CharField(blank=True, max_length=100)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('income', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('classification', models.CharField(choices=[('Student', 'Student'), ('Senior', 'Senior'), ('Employed', 'Employed')], default='Employed', max_length=20)),
                ('birth_certificate', models.BooleanField(default=False)),
                ('marriage_certificate', models.BooleanField(default=False)),
                ('application_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.CharField(blank=True, max_length=100)),
                ('reject_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaf_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'leaf_members_info',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='member',
            name='pre_member',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_member', to='members.leafmemberinfo'),
        ),
        migrations.CreateModel(
            name='SeniorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('educational_attainment', models.CharField(blank=True, max_length=100)),
                ('pension_income', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='senior_profile', to='members.member')),
            ],
            options={
                'db_table': 'senior_profiles',
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=200)),
                ('year_level', models.CharField(max_length=50)),
                ('allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to='members.member')),
            ],
            options={
                'db_table': 'student_profiles',
            },
        ),
        migrations.DeleteModel(
            name='MembershipApplication',
        ),
    ]
