# Generated by Django 6.0.5 on 2026-05-17 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_remove_member_application_remove_member_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='membership_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
