# Generated by Django 6.0.5 on 2026-05-18 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_member_membership_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='leafmemberinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=100),
        ),
    ]
