# Generated by Django 6.0.5 on 2026-06-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_savings'),
    ]

    operations = [
        migrations.AddField(
            model_name='leafmemberinfo',
            name='is_f2f',
            field=models.BooleanField(default=False),
        ),
    ]
