# Generated by Django 6.0.5 on 2026-06-20 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_alter_onlineapplication_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineapplication',
            name='plain_password',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
