# Generated by Django 6.0.5 on 2026-06-28 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_onlineapplication_plain_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareCapitalTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_type', models.CharField(choices=[('Initial', 'Initial Deposit'), ('Deposit', 'Manual Deposit'), ('CBU', 'CBU from Loan')], default='Deposit', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('recorded_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_capital_transactions', to='members.member')),
            ],
            options={
                'db_table': 'share_capital_transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
