# Generated by Django 6.0.5 on 2026-06-29 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_sharecapitaltransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineapplication',
            name='id_back_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='onlineapplication',
            name='id_front_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
