# Generated by Django 6.0.3 on 2026-09-18 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_member_loan_multiplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineapplication',
            name='ocr_birthdate_match',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='onlineapplication',
            name='ocr_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='onlineapplication',
            name='ocr_extracted_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='onlineapplication',
            name='ocr_name_match',
            field=models.BooleanField(default=False),
        ),
    ]
