# Generated by Django 6.0.3 on 2026-05-10 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-pinned', '-created_at']},
        ),
        migrations.AddField(
            model_name='announcement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='announcements/'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='type',
            field=models.CharField(choices=[('Notice', 'Notice'), ('Activity', 'Activity'), ('Seminar', 'Seminar'), ('Event', 'Event'), ('Announcement', 'Announcement')], default='Notice', max_length=20),
        ),
        migrations.AlterField(
            model_name='announcementcomment',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ann_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
