# Generated by Django 6.0.3 on 2026-04-13 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('loan_type', models.CharField(choices=[('Regular Loan', 'Regular Loan'), ('Emergency Loan', 'Emergency Loan'), ('Salary Loan', 'Salary Loan'), ('Housing Loan', 'Housing Loan'), ('Business Loan', 'Business Loan'), ('Other Loan', 'Other Loan')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('term_months', models.IntegerField()),
                ('interest_rate', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('monthly_due', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('purpose', models.TextField()),
                ('collateral', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('For Review', 'For Review'), ('Approved', 'Approved'), ('Active', 'Active'), ('Completed', 'Completed'), ('Declined', 'Declined'), ('Overdue', 'Overdue')], default='For Review', max_length=15)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=50)),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('decline_reason', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='members.member')),
            ],
            options={
                'db_table': 'loans',
                'ordering': ['-applied_at'],
            },
        ),
    ]
