# Generated by Django 6.0.5 on 2026-06-29 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
        ('members', '0011_onlineapplication_id_back_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GCashPaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference_number', models.CharField(max_length=20)),
                ('screenshot_url', models.URLField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('verified_by', models.CharField(blank=True, max_length=100)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('reject_reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gcash_requests', to='loans.loan')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gcash_requests', to='members.member')),
            ],
            options={
                'db_table': 'gcash_payment_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
