# Generated by Django 6.0.3 on 2026-09-16 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_gcashpaymentrequest_paid_to_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='cbu_rate',
            field=models.DecimalField(decimal_places=4, default=0.03, max_digits=5),
        ),
        migrations.AddField(
            model_name='loan',
            name='filing_fee_amt',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=10),
        ),
        migrations.AddField(
            model_name='loan',
            name='insurance_rate',
            field=models.DecimalField(decimal_places=4, default=0.0125, max_digits=5),
        ),
        migrations.AddField(
            model_name='loan',
            name='sd_rate',
            field=models.DecimalField(decimal_places=4, default=0.01, max_digits=5),
        ),
        migrations.AddField(
            model_name='loan',
            name='service_fee_rate',
            field=models.DecimalField(decimal_places=4, default=0.03, max_digits=5),
        ),
    ]
